---
title: "<h2>Bay Segment Hydrologic Estimates & Adjustment Factors</h2>"
output: 
  html_document:
      css: styles.css
runtime: shiny
---

```{r, warning = F, message = F, echo = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F)

library(knitr)
library(tidyverse)
library(kableExtra)

# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')

data(yrests)
yrs <- unique(yrests$year)
```

```{r reactive}
tabsel <- reactive({
   
   # input 
   yrsel <- input$yrsel
   
   totab <- yrests %>% 
      filter(year == yrsel) %>% 
      select(-year, -compload) %>% 
      rename(
         `Bay segment` = bs, 
         `Hydrology estimate (mill m3)` = est, 
         Adjustment = adj, 
         `Compliance load adjustment factor` = factor#, 
         # `Compliance load` = compload
      )

   # tabular output
   out <- HTML(knitr::kable(totab, format = 'html', digits = 2) %>% 
      kable_styling(full_width = T, font_size = 14))
   
   return(out)
   
})
```

```{r}
column(12, 
       column(4, 
              selectInput('yrsel', 'Select year:', choices = yrs, selected = max(yrs))
       )
)
```

`r renderText(input$yrsel)` annual hydrologic adjustment factor results by bay segment, based upon regressions developed in [TBEP Technical Publication #03-16](https://tbeptech.org/TBEP_TECH_PUBS/2016/TBEP_03_16_TBNMC_Tech_Memo_Update_LTB_Hyd_Tool.pdf).
   
```{r, results = 'asis'}
renderUI(tabsel())
```